#!/usr/bin/env python3
"""Add generated policy adapters; preserve unrelated machine-local settings."""
import argparse, hashlib, json, os, pathlib, re, shutil

START = '<!-- shared-authorization-policy:start -->'
END = '<!-- shared-authorization-policy:end -->'
TSTART = '# shared-authorization-policy:start'
TEND = '# shared-authorization-policy:end'

def managed(text, start, end, body):
    block = start + '\n' + body.rstrip() + '\n' + end
    if start in text:
        if text.count(start) != 1 or text.count(end) != 1:
            raise ValueError('ambiguous managed block')
        return re.sub(re.escape(start)+r'.*?'+re.escape(end), lambda _:block, text, flags=re.S)
    return text.rstrip() + '\n\n' + block + '\n'

def main():
    p=argparse.ArgumentParser(); p.add_argument('--home',type=pathlib.Path,default=pathlib.Path.home()); p.add_argument('--apply',action='store_true'); args=p.parse_args()
    home=args.home.resolve(); policy=home/'.agents/authorization-policy.md'; content=policy.read_text(); digest=hashlib.sha256(content.encode()).hexdigest()
    planned={}
    def put(path,text):
        old=path.read_text() if path.exists() else ''
        if old != text: planned[path]=(old,text)
    def instruction(path,body):
        old=path.read_text() if path.exists() else ''
        put(path,managed(old,START,END,body))
    # JSON strings are valid TOML basic strings, with Unicode left literal.
    for name in ('.codex','.codex-work'):
        root=home/name; path=root/'config.toml'
        if not path.exists(): continue
        old=path.read_text(); stripped=re.sub(re.escape(TSTART)+r'.*?'+re.escape(TEND),'',old,flags=re.S)
        if re.search(r'^\s*\[auto_review\]',stripped,re.M) or re.search(r'^\s*auto_review\.',stripped,re.M):
            raise ValueError(str(path)+': existing unmanaged auto_review needs reconciliation')
        block='[auto_review]\nextra_policy = '+json.dumps(content,ensure_ascii=False)
        put(path,managed(old,TSTART,TEND,block))
        instruction(root/'AGENTS.md','Read '+policy.as_posix()+' before provider delegation or remote writes; apply it alongside project gates.')
    allow=content.split('## Authorized company GLM review\n\n',1)[1].split('\n## Payload',1)[0].strip()
    for name in ('.claude','.claude-personal'):
        root=home/name
        if not root.exists(): continue
        path=root/'settings.json'; d=json.loads(path.read_text()) if path.exists() else {}; auto=d.setdefault('autoMode',{})
        # Remove only entries generated by us; retain all custom rules and defaults.
        for key,entry in [('environment','Shared authorization policy:\n'+content),('allow','Authorized company GLM review: '+allow)]:
            prefix=entry.split(':',1)[0]+':'
            values=auto.get(key,['$defaults'])
            if not isinstance(values,list): raise ValueError('autoMode list expected')
            values=[v for v in values if not v.startswith(prefix)]
            if '$defaults' not in values: values.insert(0,'$defaults')
            values.append(entry); auto[key]=values
        put(path,json.dumps(d,indent=2,ensure_ascii=False)+'\n')
        instruction(root/'CLAUDE.md','@'+policy.as_posix())
    oc=home/'.config/opencode'
    if oc.exists():
        # JSONC merges after JSON in installed 2.x. Add isolated fields to JSONC
        # only when those fields have not already been authored there.
        path=oc/'opencode.jsonc' if (oc/'opencode.jsonc').exists() else oc/'opencode.json'
        old=path.read_text() if path.exists() else '{}\n'
        old=re.sub(r'\n// shared-authorization-policy:start.*?// shared-authorization-policy:end\n?', '', old, flags=re.S)
        instructions=[policy.as_posix()]
        if path.suffix == '.jsonc':
            if re.search(r'"(?:instructions|permission)"\s*:',old):
                raise ValueError(str(path)+': reconcile existing JSONC instructions/permission first')
            pos=old.find('{')
            if pos<0: raise ValueError('JSONC object expected')
            # No generic shell allow. These are direct tool URL guards, not egress enforcement.
            fragment=json.dumps({'instructions':instructions,'permission':{'webfetch':{'https://openrouter.ai/api/*':'ask','https://api.fireworks.ai/inference/*':'ask'}}},indent=2)[1:-1].strip()
            put(path,old[:pos+1]+'\n// shared-authorization-policy:start\n'+fragment+',\n// shared-authorization-policy:end\n'+old[pos+1:])
        else:
            d=json.loads(old); existing=d.setdefault('instructions',[])
            if instructions[0] not in existing: existing.append(instructions[0])
            perm=d.setdefault('permission',{}); web=perm.setdefault('webfetch',{})
            if not isinstance(web,dict): raise ValueError('existing scalar webfetch permission needs reconciliation')
            for url in ('https://openrouter.ai/api/*','https://api.fireworks.ai/inference/*'): web[url]='ask'
            put(path,json.dumps(d,indent=2,ensure_ascii=False)+'\n')
    print(json.dumps({'policy_sha256':digest,'apply':args.apply,'changed_paths':[str(x) for x in planned]}))
    if args.apply:
        for path,(old,new) in planned.items():
            path.parent.mkdir(parents=True,exist_ok=True)
            if path.exists():
                backup=path.with_name(path.name+'.before-shared-authorization')
                if not backup.exists(): shutil.copy2(path,backup)
            path.write_text(new)

if __name__=='__main__': main()
